-- Zayt w Mouneh secure owner dashboard backend
-- Run this only in the dedicated Zayt w Mouneh Supabase project.
-- Then create the owner Auth user and insert that user's UUID into public.admin_users.
-- Browser code must use only the publishable key. Never expose a secret/service_role key.

create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  label text not null default 'Owner',
  created_at timestamptz not null default now()
);

create table if not exists public.product_overrides (
  product_id text primary key,
  action text not null default 'upsert' check (action in ('upsert','hide')),
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('page_view','product_view','add_to_cart','whatsapp_click','search')),
  page_path text not null check (char_length(page_path) <= 300),
  session_id text check (char_length(session_id) <= 80),
  referrer_host text check (char_length(referrer_host) <= 180),
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_activity (
  id bigint generated by default as identity primary key,
  actor uuid not null references auth.users(id),
  action text not null check (char_length(action) <= 120),
  target_type text check (char_length(target_type) <= 80),
  target_id text check (char_length(target_id) <= 180),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.product_overrides enable row level security;
alter table public.site_settings enable row level security;
alter table public.site_events enable row level security;
alter table public.admin_activity enable row level security;

grant select on public.admin_users to authenticated;
grant select on public.product_overrides to anon, authenticated;
grant insert, update, delete on public.product_overrides to authenticated;
grant select on public.site_settings to anon, authenticated;
grant insert, update, delete on public.site_settings to authenticated;
grant insert on public.site_events to anon, authenticated;
grant select, delete on public.site_events to authenticated;
grant select, insert on public.admin_activity to authenticated;
grant usage, select on sequence public.site_events_id_seq to anon, authenticated;
grant usage, select on sequence public.admin_activity_id_seq to authenticated;

drop policy if exists "admins can read own membership" on public.admin_users;
create policy "admins can read own membership"
on public.admin_users for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "public can read product overrides" on public.product_overrides;
create policy "public can read product overrides"
on public.product_overrides for select
to anon, authenticated
using (true);

drop policy if exists "admins can insert product overrides" on public.product_overrides;
create policy "admins can insert product overrides"
on public.product_overrides for insert
to authenticated
with check (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
  and updated_by = (select auth.uid())
);

drop policy if exists "admins can update product overrides" on public.product_overrides;
create policy "admins can update product overrides"
on public.product_overrides for update
to authenticated
using (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
  and updated_by = (select auth.uid())
);

drop policy if exists "admins can delete product overrides" on public.product_overrides;
create policy "admins can delete product overrides"
on public.product_overrides for delete
to authenticated
using (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
);

drop policy if exists "public can read site settings" on public.site_settings;
create policy "public can read site settings"
on public.site_settings for select
to anon, authenticated
using (true);

drop policy if exists "admins can insert site settings" on public.site_settings;
create policy "admins can insert site settings"
on public.site_settings for insert
to authenticated
with check (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
  and updated_by = (select auth.uid())
);

drop policy if exists "admins can update site settings" on public.site_settings;
create policy "admins can update site settings"
on public.site_settings for update
to authenticated
using (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
  and updated_by = (select auth.uid())
);

drop policy if exists "admins can delete site settings" on public.site_settings;
create policy "admins can delete site settings"
on public.site_settings for delete
to authenticated
using (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
);

drop policy if exists "site can insert analytics events" on public.site_events;
create policy "site can insert analytics events"
on public.site_events for insert
to anon, authenticated
with check (
  event_name in ('page_view','product_view','add_to_cart','whatsapp_click','search')
  and char_length(page_path) <= 300
  and coalesce(char_length(session_id), 0) <= 80
  and coalesce(char_length(referrer_host), 0) <= 180
);

drop policy if exists "admins can read analytics events" on public.site_events;
create policy "admins can read analytics events"
on public.site_events for select
to authenticated
using (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
);

drop policy if exists "admins can delete analytics events" on public.site_events;
create policy "admins can delete analytics events"
on public.site_events for delete
to authenticated
using (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
);

drop policy if exists "admins can read activity" on public.admin_activity;
create policy "admins can read activity"
on public.admin_activity for select
to authenticated
using (
  actor = (select auth.uid())
  and exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
);

drop policy if exists "admins can insert activity" on public.admin_activity;
create policy "admins can insert activity"
on public.admin_activity for insert
to authenticated
with check (
  actor = (select auth.uid())
  and exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  true,
  10485760,
  array['image/jpeg','image/png','image/webp','image/avif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public can view product images" on storage.objects;
create policy "public can view product images"
on storage.objects for select
to public
using (bucket_id = 'product-images');

drop policy if exists "admins can upload product images" on storage.objects;
create policy "admins can upload product images"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'product-images'
  and exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
);

drop policy if exists "admins can update product images" on storage.objects;
create policy "admins can update product images"
on storage.objects for update
to authenticated
using (
  bucket_id = 'product-images'
  and exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
)
with check (
  bucket_id = 'product-images'
  and exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
);

drop policy if exists "admins can delete product images" on storage.objects;
create policy "admins can delete product images"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'product-images'
  and exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
);

insert into public.site_settings (key, value)
values
  ('announcement', '{"enabled": true, "en": "Authentic Lebanese pantry essentials · Since 2006", "ar": "مونة لبنانية أصيلة · منذ 2006"}'::jsonb),
  ('contact', '{"whatsapp": "96181581230"}'::jsonb),
  ('promo', '{"enabled": false, "titleEn": "", "titleAr": "", "bodyEn": "", "bodyAr": ""}'::jsonb)
on conflict (key) do nothing;

-- One-time owner setup example (replace with the real Auth user UUID):
-- insert into public.admin_users (user_id, label)
-- values ('00000000-0000-0000-0000-000000000000', 'Owner');
