const STATIC_CANONICAL_HOST = "https://zaytwmouneh.veyro-202.workers.dev";
const PUBLIC_ROUTES = new Set(["/", "/shop", "/gift", "/recipes", "/about", "/contact", "/privacy", "/terms"]);
let catalogueCache = null, photoCache = null, configCache = null;
let overridesCache = { at: 0, rows: [] };
const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const cleanArabic=v=>String(v||"").replace(/[\u202a-\u202e\u2066-\u2069]/g,"").trim();
const jsonScript=v=>JSON.stringify(v).replace(/</g,"\\u003c");
const money=v=>"$"+Number(v||0).toFixed(2);
async function assetText(env,path){const r=await env.ASSETS.fetch(new Request("https://assets.local"+path));if(!r.ok)throw new Error("Asset not found: "+path);return r.text()}
async function catalogue(env){
 if(catalogueCache)return catalogueCache;
 const text=await assetText(env,"/products-data.js"),m=text.match(/const PRODUCTS_DATA\s*=\s*(\[[\s\S]*?\]);/);
 if(!m)throw new Error("Catalogue parse failed");
 const products=JSON.parse(m[1]),am=text.match(/const aliases\s*=\s*(\{[\s\S]*?\});/);
 if(am)try{const aliases=JSON.parse(am[1]);for(const [a,c] of Object.entries(aliases)){const ai=products.findIndex(x=>x.id===a),cp=products.find(x=>x.id===c);if(ai<0||!cp)continue;const ap=products[ai],seen=new Set((cp.variants||[]).map(v=>v.id));cp.variants=[...(cp.variants||[]),...(ap.variants||[]).filter(v=>!seen.has(v.id))].sort((x,y)=>Number(x.price)-Number(y.price));products.splice(ai,1)}}catch{}
 catalogueCache=products;return products
}
async function photos(env){if(photoCache)return photoCache;try{const text=await assetText(env,"/product-photos.js"),m=text.match(/const map\s*=\s*(\{[\s\S]*?\n\s*\});/);photoCache=m?JSON.parse(m[1]):{}}catch{photoCache={}}return photoCache}
async function publicConfig(env){if(configCache)return configCache;try{const text=await assetText(env,"/admin-config.js");configCache={supabaseUrl:text.match(/supabaseUrl:\s*["']([^"']+)/)?.[1]||"",supabasePublishableKey:text.match(/supabasePublishableKey:\s*["']([^"']+)/)?.[1]||""}}catch{configCache={supabaseUrl:"",supabasePublishableKey:""}}return configCache}
async function overrides(env){
 const now=Date.now();if(now-overridesCache.at<60000)return overridesCache.rows;
 const c=await publicConfig(env);if(!c.supabaseUrl||!c.supabasePublishableKey)return overridesCache.rows;
 try{const r=await fetch(c.supabaseUrl.replace(/\/$/,"")+"/rest/v1/product_overrides?select=product_id,action,payload",{headers:{apikey:c.supabasePublishableKey},cf:{cacheTtl:60,cacheEverything:true}});if(r.ok){const rows=await r.json();overridesCache={at:now,rows:Array.isArray(rows)?rows:[]}}}catch{}
 return overridesCache.rows
}
function mergeProducts(base,rows){const map=new Map(base.map(p=>[p.id,structuredClone(p)]));for(const row of rows||[]){let p=map.get(row.product_id)||{id:row.product_id,variants:[]};if(row.payload&&typeof row.payload==="object")p={...p,...row.payload};p.__hidden=row.action==="hide";map.set(row.product_id,p)}return [...map.values()].filter(p=>!p.__hidden)}
function description(p){const sizes=(p.variants||[]).map(v=>v.sizeEn).filter(Boolean).slice(0,4).join(", ");return p.nameEn+" from Zayt w Mouneh's Lebanese pantry"+(sizes?", available in "+sizes:"")+". View current sizes and prices, then add it to your pantry for website checkout."}
function schema(p,origin,photo){const variants=p.variants||[],prices=variants.map(v=>Number(v.price)).filter(Number.isFinite),d={"@context":"https://schema.org","@type":"Product",name:p.nameEn,alternateName:cleanArabic(p.nameAr),sku:p.id,category:p.category,brand:{"@type":"Brand",name:"Zayt w Mouneh"},url:origin+"/products/"+encodeURIComponent(p.id),description:description(p)};if(photo?.url)d.image=[origin+"/"+String(photo.url).replace(/^\//,"")];if(prices.length)d.offers={"@type":"AggregateOffer",priceCurrency:"USD",lowPrice:Math.min(...prices).toFixed(2),highPrice:Math.max(...prices).toFixed(2),offerCount:variants.length,url:origin+"/shop?product="+encodeURIComponent(p.id)+"#shop"};return d}
function page(p,origin,photo){
 const ar=cleanArabic(p.nameAr),variants=p.variants||[],prices=variants.map(v=>Number(v.price)||0),min=prices.length?Math.min(...prices):0,max=prices.length?Math.max(...prices):0,price=min===max?money(min):money(min)+"–"+money(max),canonical=origin+"/products/"+encodeURIComponent(p.id),shop="/shop?product="+encodeURIComponent(p.id)+"#shop",cat="/shop?category="+encodeURIComponent(p.category||"")+"#shop",desc=description(p);
 const media=photo?.url?'<img src="/'+esc(String(photo.url).replace(/^\//,""))+'" alt="'+esc(p.nameEn)+'" width="'+(Number(photo.width)||900)+'" height="'+(Number(photo.height)||900)+'" loading="eager" decoding="async">':'<div class="product-placeholder" aria-hidden="true"><img src="/assets/logo.svg?v=20261002-1005" alt=""></div>';
 const rows=variants.map(v=>'<li><span><b>'+esc(v.sizeEn||"")+'</b><small lang="ar" dir="rtl">'+esc(cleanArabic(v.sizeAr))+'</small></span><strong>'+money(v.price)+'</strong></li>').join("");
 return '<!doctype html><html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0f4a20"><title>'+esc(p.nameEn)+' | Zayt w Mouneh</title><meta name="description" content="'+esc(desc)+'"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="'+esc(canonical)+'"><meta property="og:type" content="product"><meta property="og:title" content="'+esc(p.nameEn)+' | Zayt w Mouneh"><meta property="og:description" content="'+esc(desc)+'"><meta property="og:url" content="'+esc(canonical)+'">'+(photo?.url?'<meta property="og:image" content="'+esc(origin+"/"+String(photo.url).replace(/^\//,""))+'">':"")+'<link rel="icon" type="image/svg+xml" href="/assets/favicon.svg?v=20261003-round1"><link rel="stylesheet" href="/product-page.css?v=20261005-hardening1"><script type="application/ld+json">'+jsonScript(schema(p,origin,photo))+'</script></head><body><header class="product-header"><a class="brand" href="/"><img src="/assets/logo.svg?v=20261002-1005" alt="Zayt w Mouneh"><span>Zayt w Mouneh</span></a><nav><a href="/shop">Shop</a><a href="/gift">Gifts</a><a href="/recipes">Recipes</a><a href="/account">Account</a></nav></header><main><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span>›</span><a href="'+esc(cat)+'">'+esc(p.category||"Pantry")+'</a><span>›</span><span>'+esc(p.nameEn)+'</span></nav><section class="product-shell"><div class="product-media">'+media+'</div><div class="product-copy"><p class="eyebrow">'+esc(p.category||"Lebanese pantry")+'</p><h1>'+esc(p.nameEn)+'</h1>'+(ar?'<p class="arabic-name" lang="ar" dir="rtl">'+esc(ar)+'</p>':"")+'<p class="lede">'+esc(desc)+'</p><div class="price-line"><strong>'+esc(price)+'</strong><span>USD · product price</span></div><div class="variants"><h2>Sizes & prices <span lang="ar" dir="rtl">الأحجام والأسعار</span></h2><ul>'+rows+'</ul></div><a class="primary" href="'+esc(shop)+'">Choose size & add to pantry <span>→</span></a><a class="secondary" href="/shop">Back to the full pantry</a><p class="fineprint">Availability, delivery details and the final payable total are confirmed during website checkout and in your order updates. WhatsApp remains available for support.</p></div></section><section class="product-assurance"><article><b>Website checkout</b><span>Place the order directly on the site.</span></article><article><b>Delivery across Lebanon</b><span>Area, fee and timing are shown or confirmed with the order.</span></article><article><b>Account optional</b><span>Guest checkout works; signing in adds points and order history.</span></article></section></main><footer><span>© '+new Date().getUTCFullYear()+' Zayt w Mouneh</span><nav><a href="/terms">Terms</a><a href="/privacy">Privacy</a><a href="https://wa.me/96181581230" rel="noopener">WhatsApp support</a></nav></footer></body></html>'
}
async function products(env){const [b,o]=await Promise.all([catalogue(env),overrides(env)]);return mergeProducts(b,o)}
const securityHeaders={"X-Content-Type-Options":"nosniff","Referrer-Policy":"strict-origin-when-cross-origin","X-Frame-Options":"DENY","Content-Security-Policy":"default-src 'self' https: data: blob:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' https: data: blob:; font-src 'self' https: data:; connect-src 'self' https://*.supabase.co wss://*.supabase.co; object-src 'none'; base-uri 'self'; frame-ancestors 'none'"};
async function productResponse(request,env,id){const [all,pm]=await Promise.all([products(env),photos(env)]),p=all.find(x=>x.id===id);if(!p)return new Response("Product not found",{status:404,headers:{"Content-Type":"text/plain; charset=utf-8","X-Robots-Tag":"noindex"}});return new Response(page(p,new URL(request.url).origin,pm[id]),{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"public, max-age=300, s-maxage=3600, stale-while-revalidate=86400",...securityHeaders}})}
async function sitemap(request,env){const all=await products(env),origin=new URL(request.url).origin,paths=["/","/shop","/gift","/recipes","/about","/contact","/privacy","/terms",...all.map(p=>"/products/"+encodeURIComponent(p.id))],xml='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+paths.map(p=>"  <url><loc>"+esc(origin+p)+"</loc></url>").join("\n")+"\n</urlset>";return new Response(xml,{headers:{"Content-Type":"application/xml; charset=utf-8","Cache-Control":"public, max-age=300, s-maxage=3600"}})}
function robots(request){const origin=new URL(request.url).origin;return new Response("User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /admin.html\nDisallow: /admin-config.js\nDisallow: /checkout\nDisallow: /account\nSitemap: "+origin+"/sitemap.xml\n",{headers:{"Content-Type":"text/plain; charset=utf-8","Cache-Control":"public, max-age=3600"}})}
const clean=p=>p==="/"?"/":(p.replace(/\.html$/,"").replace(/\/$/,"")||"/");
async function canonicalAsset(request,env){const asset=await env.ASSETS.fetch(request),type=asset.headers.get("content-type")||"";if(!asset.ok||!type.includes("text/html"))return asset;const url=new URL(request.url),origin=url.origin,canonical=origin+clean(url.pathname);let html=await asset.text();html=html.replaceAll(STATIC_CANONICAL_HOST,origin).replace(/<link rel="canonical" href="[^"]*">/i,'<link rel="canonical" href="'+esc(canonical)+'">').replace(/<meta property="og:url" content="[^"]*">/i,'<meta property="og:url" content="'+esc(canonical)+'">');const headers=new Headers(asset.headers);headers.set("Content-Type","text/html; charset=utf-8");headers.set("Cache-Control","no-cache, must-revalidate");return new Response(html,{status:asset.status,headers})}
export default{async fetch(request,env){const url=new URL(request.url);if(request.method!=="GET"&&request.method!=="HEAD")return env.ASSETS.fetch(request);if(url.pathname==="/sitemap.xml")return sitemap(request,env);if(url.pathname==="/robots.txt")return robots(request);if(url.pathname==="/products")return Response.redirect(url.origin+"/shop",301);const m=url.pathname.match(/^\/products\/([a-z0-9-]+)\/?$/i);if(m)return productResponse(request,env,decodeURIComponent(m[1]));if(PUBLIC_ROUTES.has(clean(url.pathname)))return canonicalAsset(request,env);return env.ASSETS.fetch(request)}};