create table if not exists private.return_order_access_tokens (
  id uuid primary key default gen_random_uuid(),
  order_reference text not null references public.orders(reference) on delete cascade,
  token_hash text not null unique check (char_length(token_hash)=64),
  issued_to_user uuid references auth.users(id) on delete cascade,
  ip_hash text not null check (char_length(ip_hash) between 32 and 128),
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists return_order_access_tokens_ref_exp_idx on private.return_order_access_tokens(order_reference,expires_at);
create index if not exists return_order_access_tokens_exp_idx on private.return_order_access_tokens(expires_at);
alter table private.return_order_access_tokens enable row level security;
revoke all on private.return_order_access_tokens from public,anon,authenticated;

create table if not exists private.return_order_lookup_attempts (
  id bigint generated by default as identity primary key,
  ip_hash text not null check (char_length(ip_hash) between 32 and 128),
  order_reference_hash text not null check (char_length(order_reference_hash)=64),
  success boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists return_order_lookup_attempts_ip_idx on private.return_order_lookup_attempts(ip_hash,created_at desc);
create index if not exists return_order_lookup_attempts_ref_idx on private.return_order_lookup_attempts(ip_hash,order_reference_hash,created_at desc);
alter table private.return_order_lookup_attempts enable row level security;
revoke all on private.return_order_lookup_attempts from public,anon,authenticated;

create or replace function private.zwm_return_order_access(p_ref text,p_claim text default null)
returns boolean
language plpgsql stable security definer set search_path=''
as $$
declare
  u uuid:=auth.uid();
  o public.orders;
  l mouneh.order_links;
  claim text:=coalesce(p_claim,'');
begin
  select * into o from public.orders where reference=p_ref;
  if o.reference is null then return false; end if;

  if u is not null and exists(select 1 from public.admin_users a where a.user_id=u) then
    return true;
  end if;

  select * into l from mouneh.order_links where reference=p_ref;
  if u is not null and (o.customer_id=u or l.user_id=u) then
    return true;
  end if;

  if l.user_id is null and length(claim)>=64 and l.claim_hash=md5(claim) then
    return true;
  end if;

  if length(claim)>=64 and exists(
    select 1 from private.return_order_access_tokens t
    where t.order_reference=p_ref
      and t.token_hash=encode(extensions.digest(claim,'sha256'),'hex')
      and t.expires_at>now()
  ) then
    return true;
  end if;

  return false;
end
$$;
revoke all on function private.zwm_return_order_access(text,text) from public,anon,authenticated;

create or replace function public.zwm_return_verify_order(
  p_reference text,
  p_contact text default null,
  p_ip_hash text default null,
  p_user_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  ref text:=upper(trim(coalesce(p_reference,'')));
  contact text:=trim(coalesce(p_contact,''));
  ip text:=trim(coalesce(p_ip_hash,''));
  ref_hash text;
  o public.orders;
  l mouneh.order_links;
  user_owns boolean:=false;
  contact_ok boolean:=false;
  contact_digits text;
  order_digits text;
  failed_ip integer:=0;
  failed_ref integer:=0;
  token text;
  expiry timestamptz:=now()+interval '30 minutes';
  context jsonb;
begin
  if char_length(ref) not between 6 and 80 or ref !~ '^[A-Z0-9-]+$' then
    raise exception 'Order details could not be verified';
  end if;
  if char_length(ip) not between 32 and 128 then
    raise exception 'Verification unavailable';
  end if;
  if char_length(contact)>254 then
    raise exception 'Order details could not be verified';
  end if;

  delete from private.return_order_access_tokens where expires_at<=now();
  delete from private.return_order_lookup_attempts where created_at<now()-interval '24 hours';

  ref_hash:=encode(extensions.digest(ref,'sha256'),'hex');

  select count(*) into failed_ip
  from private.return_order_lookup_attempts a
  where a.ip_hash=ip and not a.success and a.created_at>now()-interval '15 minutes';

  select count(*) into failed_ref
  from private.return_order_lookup_attempts a
  where a.ip_hash=ip and a.order_reference_hash=ref_hash
    and not a.success and a.created_at>now()-interval '15 minutes';

  if failed_ip>=20 or failed_ref>=6 then
    raise exception 'Too many verification attempts. Please try again later.';
  end if;

  select * into o from public.orders where reference=ref;
  if o.reference is not null then
    select * into l from mouneh.order_links where reference=ref;
    user_owns:=p_user_id is not null and (o.customer_id=p_user_id or l.user_id=p_user_id);

    if not user_owns and contact<>'' then
      if position('@' in contact)>0 then
        contact_ok:=lower(trim(coalesce(o.customer_email,'')))=lower(contact);
      else
        contact_digits:=regexp_replace(contact,'[^0-9]+','','g');
        order_digits:=regexp_replace(coalesce(o.customer_phone,''),'[^0-9]+','','g');
        contact_ok:=char_length(contact_digits)>=7
          and char_length(order_digits)>=7
          and (
            contact_digits=order_digits
            or (
              char_length(contact_digits)>=8
              and char_length(order_digits)>=8
              and right(contact_digits,8)=right(order_digits,8)
            )
          );
      end if;
    end if;
  end if;

  if o.reference is null or (not user_owns and not contact_ok) then
    insert into private.return_order_lookup_attempts(ip_hash,order_reference_hash,success)
    values(ip,ref_hash,false);
    raise exception 'Order details could not be verified';
  end if;

  token:=encode(extensions.gen_random_bytes(32),'hex');

  insert into private.return_order_access_tokens(order_reference,token_hash,issued_to_user,ip_hash,expires_at)
  values(ref,encode(extensions.digest(token,'sha256'),'hex'),p_user_id,ip,expiry);

  insert into private.return_order_lookup_attempts(ip_hash,order_reference_hash,success)
  values(ip,ref_hash,true);

  context:=private.zwm_returns('order_context',jsonb_build_object('reference',ref,'claim_token',token));

  return jsonb_build_object('access_token',token,'expires_at',expiry,'context',context);
end
$$;

revoke all on function public.zwm_return_verify_order(text,text,text,uuid) from public,anon,authenticated;
grant execute on function public.zwm_return_verify_order(text,text,text,uuid) to service_role;
