-- Zayt w Mouneh production notification infrastructure.
create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron;

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  audience text not null check (audience in ('admin','customer')),
  notification_type text not null check (char_length(notification_type) between 1 and 80),
  category text not null check (category in ('new_order','wholesale','payment_issue','customer_requests','reviews','inventory','order_updates','back_in_stock','mouneh_points','marketing','routine','test')),
  entity_type text not null check (char_length(entity_type) between 1 and 80),
  entity_id text not null check (char_length(entity_id) between 1 and 220),
  title_key text not null check (char_length(title_key) between 1 and 120),
  body_key text not null check (char_length(body_key) between 1 and 120),
  title_args jsonb not null default '{}'::jsonb check (jsonb_typeof(title_args)='object'),
  body_args jsonb not null default '{}'::jsonb check (jsonb_typeof(body_args)='object'),
  route text not null check (char_length(route) between 1 and 500 and route like '/%' and route not like '//%' and route !~ '[[:cntrl:]]'),
  priority text not null default 'important' check (priority in ('critical','important','informational')),
  read_at timestamptz,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  dedupe_key text not null check (char_length(dedupe_key) between 1 and 260),
  unique(user_id,dedupe_key)
);
create table public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  audience text not null check (audience in ('admin','customer')),
  endpoint text not null check (char_length(endpoint) between 16 and 4096),
  p256dh text not null check (char_length(p256dh) between 20 and 512),
  auth_key text not null check (char_length(auth_key) between 8 and 256),
  device_label text check (device_label is null or char_length(device_label) <= 100),
  locale text not null default 'en' check (locale in ('en','ar','fr')),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_used_at timestamptz not null default now(),
  last_success_at timestamptz,
  failure_count integer not null default 0 check (failure_count >= 0),
  revoked_at timestamptz,
  unique(endpoint,audience)
);
create table public.notification_preferences (
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null check (category in ('new_order','wholesale','payment_issue','customer_requests','reviews','inventory','order_updates','back_in_stock','mouneh_points','marketing','routine')),
  in_app_enabled boolean not null default true,
  push_enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key(user_id,category)
);
create table private.notification_push_outbox (
  id uuid primary key default gen_random_uuid(),
  notification_id uuid not null unique references public.notifications(id) on delete cascade,
  target_subscription_id uuid references public.push_subscriptions(id) on delete set null,
  status text not null default 'pending' check (status in ('pending','processing','sent','retry','dead','no_subscriptions','disabled')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  last_error text check (last_error is null or char_length(last_error) <= 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table private.notification_delivery_log (
  id bigint generated by default as identity primary key,
  notification_id uuid not null references public.notifications(id) on delete cascade,
  outbox_id uuid not null references private.notification_push_outbox(id) on delete cascade,
  subscription_id uuid references public.push_subscriptions(id) on delete set null,
  delivery_state text not null check (delivery_state in ('accepted','permanent_failure','temporary_failure','skipped')),
  error_category text check (error_category is null or char_length(error_category) <= 120),
  created_at timestamptz not null default now()
);
create index notifications_user_created_idx on public.notifications(user_id,created_at desc);
create index notifications_user_unread_idx on public.notifications(user_id,created_at desc) where read_at is null;
create index notifications_entity_idx on public.notifications(entity_type,entity_id);
create index push_subscriptions_user_active_idx on public.push_subscriptions(user_id,audience,enabled) where revoked_at is null;
create index notification_preferences_user_idx on public.notification_preferences(user_id);
create index notification_outbox_due_idx on private.notification_push_outbox(status,next_attempt_at) where status in ('pending','retry');
create index notification_delivery_log_notification_idx on private.notification_delivery_log(notification_id,created_at desc);
alter table public.notifications enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.notification_preferences enable row level security;
revoke all on table public.notifications from public, anon, authenticated;
revoke all on table public.push_subscriptions from public, anon, authenticated;
revoke all on table public.notification_preferences from public, anon, authenticated;
revoke all on table private.notification_push_outbox from public, anon, authenticated;
revoke all on table private.notification_delivery_log from public, anon, authenticated;
grant select on table public.notifications to authenticated;
create policy "users read own notifications" on public.notifications for select to authenticated using ((select auth.uid()) = user_id);